version: "3.9"
services:
  web:
    build: services/frontend
    ports:
      - "5000:5000"
    networks:
      - frontend
      - backend
    env_file:
      - ./.env
    depends_on: 
      - reader
      - writer
    volumes: 
      - ./services/frontend:/app      

  reader:
    build: services/reader
    ports:
      - "8081:8081"
    networks:
      - frontend
      - backend
    env_file:
      - ./.env
    depends_on:
      - redis      

  writer:
    build: services/writer
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend
    env_file:
      - ./.env
    depends_on:
      - redis      

  redis:
    image: "redis:alpine"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["--requirepass ${REDIS_PASSWORD}"]
    networks:
      - backend
    env_file:
      - ./.env

networks:
  frontend:
  backend:

volumes:
  app:
    driver: local
